server:
  port: 8088
spring:
  thymeleaf:
    mode: HTML
  datasource:
    username: root
    password: aaa
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qin_test?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource

